security:
    encoders:
        CA\UserBundle\Entity\User: sha512



    role_hierarchy:
        ROLE_SECRETAIRE: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_SECRETAIRE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main_login:
            #pattern: ^/login
            #anonymous: true
            
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path:            ca_courrier_home
            remember_me:
                secret:        %secret%
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/phenix-courrier, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/register, roles: ROLE_ADMIN }