<?php

namespace CA\CourrierBundle\Repository;

/**
 * AffiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliationRepository extends \Doctrine\ORM\EntityRepository
{
}
