<?php

namespace CA\CourrierBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AttribtionUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributionUserRepository extends \Doctrine\ORM\EntityRepository
{
      public function getCourriers($page, $nbPerPage, $type, $archived, $status, $userId)
      {
        $query = $this->_em->createQueryBuilder()
                      ->select('a', 'b', 'c')
                      ->from('CACourrierBundle:AttributionUser', 'a')
                      ->leftJoin('CACourrierBundle:Attribution', 'b', 'WITH', 'b.id = a.attribution')
                      ->leftJoin('CACourrierBundle:Courrier', 'c', 'WITH', 'b.courrier = c.id')
                      ->where('a.user = :id');
          
          if ("true" === $type):
            $query->andwhere('c.type = true');
          elseif ("false" === $type):
            $query->andwhere('c.type = false');
          endif;

          if ("true" === $archived):
            $query->andwhere('a.archived = true');
          elseif ("false" === $archived):
            $query->andwhere('a.archived = false');
          endif;

          if (is_null($status)):
            $query->andwhere('1 = 1');
          elseif (2 === $status):
            $query->andwhere('a.statut <= 2');
          else:
            $query->andwhere('a.statut = :status');
          endif;

          $query
              ->orderBy('c.createdAt', 'DESC')
              ->setParameter('id', $userId)
              ->setParameter('status', $status)
              ->getQuery();

          $query
              ->setFirstResult(($page-1) * $nbPerPage)
              ->setMaxResults($nbPerPage)
        ;
        return new Paginator($query, true);
      }
}
