<?php

namespace CA\CourrierBundle\Repository;

/**
 * AttributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributionRepository extends \Doctrine\ORM\EntityRepository
{
}
