<?php

namespace CA\CourrierBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespondantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespondantRepository extends EntityRepository
{
  public function getLikeQueryBuilder($pattern)
  {
    return $this
      ->createQueryBuilder('c')
      ->where('c.nom LIKE :pattern')
      ->setParameter('pattern', $pattern)
    ;
  }
}
