ca_courrier_home:
    path:     /{page}/{type}/{lu}/{attribuated}/{archived}
    defaults:
        _controller: CACourrierBundle:Courrier:index
        page: 1
        type: null
        lu: null
        attribuated: null
        archived: null
    requirements:
        page: \d*
        #type:  true|false|null
        #lu: true|false|null
        #attribuated: true|false|null
        #archived: true|false|null

ca_courrier_view:
    path:     /courrier/{id}
    defaults:
        _controller: CACourrierBundle:Courrier:view
    requirements:
        id: \d+

ca_courrier_add:
    path:     /add
    defaults:
        _controller: CACourrierBundle:Courrier:add

ca_courrier_edit:
    path:     /edit/{id}
    defaults:
        _controller: CACourrierBundle:Courrier:edit
    requirements:
        id: \d+

ca_courrier_delete:
    path:     /delete/{id}
    defaults:
        _controller: CACourrierBundle:Courrier:delete
    requirements:
        id: \d+

ca_courrier_archive:
    path:     /archive/{id}
    defaults:
        _controller: CACourrierBundle:Courrier:archive
    requirements:
        id: \d+

ca_courrier_attribuate:
    path:     /attribuate/{id}
    defaults:
        _controller: CACourrierBundle:Courrier:attribuate
    requirements:
        id: \d+

ca_courrier_reattribuate:
    path:     /reattribuate/{id}
    defaults:
        _controller: CACourrierBundle:Courrier:reattribuate
    requirements:
        id: \d+

ca_courrier_attribution_home:
    path:     /list-attribuation/{page}/{type}/{status}/{archived}
    defaults:
        _controller: CACourrierBundle:Courrier:listAttribuate
        page: 1
        type: null
        status: null
        archived: null
    requirements:
        page: \d*

