<?php

namespace CA\UserBundle\Repository;

/**
 * OrganigrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganigrammeRepository extends \Doctrine\ORM\EntityRepository
{
      public function getQueryBuilder()
      {
        return $this
          ->createQueryBuilder('o')
        ;
      }
    
      public function getSonQueryBuilder()
      {
        return $this
          ->createQueryBuilder('o')
        ;
      }
}
