<?php

namespace CA\UserBundle\Repository;

/**
 * TaglevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaglevelRepository extends \Doctrine\ORM\EntityRepository
{
      public function getQueryBuilder()
      {
        return $this
          ->createQueryBuilder('tl')
          ->orderBy('tl.tag', 'ASC')
        ;
      }
}
