<?php

namespace CA\UserBundle\Repository;

/**
 * TagpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagpositionRepository extends \Doctrine\ORM\EntityRepository
{
      public function getQueryBuilder()
      {
        return $this
          ->createQueryBuilder('tp')
          ->orderBy('tp.tag', 'ASC')
        ;
      }
}
